Feature/invite service
hypha-dao/hypha_wallet pull request #210
Opened 2023-07-19 03:30 UTC by n13

- Added invite service
- Changed config to have different ppp services for all networks
- Parsing ppp service config from config file

2023-07-19 22:59 UTC, gguijarro-c-chwy requested changes
Changes look good. pls fix typo

2023-07-19 22:59 UTC, gguijarro-c-chwy commented on assets/config/profile_serivce/config.json
assets/config/profile_serivce/config.json
assets/config/profile_service/config.json

2023-07-19 22:59 UTC, gguijarro-c-chwy commented on assets/config/profile_serivce/config.json
Where is this file coming from? Is this a AWS config?

2023-07-19 22:59 UTC, gguijarro-c-chwy commented
Linter is failing too

2023-07-19 23:46 UTC, n13 commented
Fixed typo

IDK what linter is complaining about seems to be something internal to GH actions

2023-07-20 01:43 UTC, gguijarro-c-chwy approved these changes

2023-07-20 01:54 UTC, merged